import { defineConfig } from 'vite';

// The game runs entirely from static files — no ROM at runtime (Hard rule #1).
// static/ is generated by `npm run setup` (JSON mirror + gfx/**) and served at
// the site root (DECISIONS #16, #17).
export default defineConfig({
  root: '.',
  publicDir: 'static',
  base: '/',
  // No SPA fallback: a missing asset is a real 404 (as the old in-browser ROM
  // path returned), not index.html with a 200 that the JSON loaders choke on.
  appType: 'mpa',
});
